import Head from 'next/head'
import HeaderGB from '../components/Accueil/GB/HeaderGB'
import SectionPresentationGB from '../components/Accueil/GB/SectionPresentationGB'
import FooterGB from '../components/Accueil/GB/FooterGB'



export default function HomeGB() { 
  
  

  return (
    <div>
      <Head>
        <title>DeFi Lottery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="image/logo-onglet.jpg"/>
      </Head>
      <HeaderGB/>
        <div className="splitchange">
          <h4>
            <a className="splitchange-more" href="#presentation">
              {" "}
              Learn more about the project{" "}
              <i className="fa-solid fa-chevron-down" />
            </a>
          </h4>
        </div>
        <SectionPresentationGB/>
        <FooterGB/>
      </div>
  )
}
