import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { FR, GB, BR } from 'country-flag-icons/react/3x2'



export default function HomeBR() { 
  
  

  return (
    <div>
      <Head>
        <title>DeFi Lottery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="image/logo-onglet.jpg"/>
      </Head>
      
      <header>
          <nav>
            <ul>
              <li id="logo">
                <a href="#">
                  <i className="fa-solid fa-ticket" /> DeFi Lottery
                </a>
              </li>
              <div className="action">
                <div className="profile" >
                  <li className="reglage">
                    <Link href="/">
                    <a className="Réglages du site">
                      <FR width={23}/>
                    </a>
                    </Link>
                  </li>
                  <li className="reglage">
                    <Link href="/HomeGB">
                    <a className="Réglages du site">
                      <GB width={23}/>
                    </a>
                    </Link>
                  </li>
                  <li className="reglage">
                    <a className="Réglages du site">
                      <BR width={23}/><i className="fa-solid fa-circle-check" />
                    </a>
                  </li>
                </div>
                </div>
              <div className="iconsnavbartwitter">
                <a
                  className="logotwitter"
                  href="https://twitter.com/?lang=fr"
                  title="Accédez à notre twitter"
                >
                  <i className="fa-brands fa-twitter" />
                </a>
              </div>
              <div className="iconsnavbardiscord">
                <a
                  className="logodiscord"
                  href="https://discord.gg/GqsyHETQM2"
                  title="Accédez à notre discord communautaire officiel"
                >
                  <i className="fa-brands fa-discord" />
                </a>
              </div>
              <li id="whitepaper">
                <a target="_blank" href="youtube.com" title="Accédez au White Paper">
                  White Paper
                </a>
              </li>
              <li id="apropos">
                <a href="#about" title="Pour mieux comprendre notre projet">
                  cerca de
                </a>
              </li>
              <li className="nav-roadmap">
                <a href="FRroadmap.html">Roteiro</a>
              </li>
              <button id="btnmarketplace" title="Accédez à la collection NFT">
                <Link href="/Mint">
                <a>Mercado NFT</a>
                </Link>
              </button>
            </ul>
          </nav>
          <div id="mainPage-home">
            <div className="mainPage-text">
              <h1>DeFi Lottery</h1>
              <div id="premierTrait" />
              <h3>100% descentralizado, 100% seguro</h3>
              <h3>
              Loteria administrada por <strong>voce</strong>
              </h3>
            </div>
            {/* <div class="mainPage-btn">
                <ul>
                    <li><a class="mainPage-btn-discover" href="#">YOU</a></li>
                    <li><a class="mainPage-btn-gettingstart" href="#">FUCK</a></li>
                </ul>
            </div> */}
          </div>
        </header>
        <div className="splitchange">
          <h4>
            <a className="splitchange-more" href="#presentation">
              {" "}
              Saiba mais sobre o projeto{" "}
              <i className="fa-solid fa-chevron-down" />
            </a>
          </h4>
        </div>
        <section id="presentation">
          <div id="about">
            <div className="about-textcontainer">
              <div className="textTitleLeft">
                <h2>Explicação do projeto</h2>
              </div>
              <div className="textParagrapheLeft">
                <p>
                DeFi Lottery é uma loteria <strong>100% Descentralizada</strong>,
                usamos tecnologias{" "}
                  <strong>BLOCKCHAIN ​​​​e NFTs</strong>.NFTs DeFi Lottery{" "}
                  <strong>NÃO SÃO simples png,jpeg</strong>,são{" "}
                  <strong>bilhetes de entrada</strong> para uma loteria semanal! Após o sorteio, você pode manter <strong>SEUS NFTs, SEUS tíquetes</strong>
                  .Assim que um vencedor for sorteado <strong>&quot;automaticamente&quot;</strong>,
                  e de forma que{" "}
                  <strong>NINGUÉM PODE INFLUENCIAR O RESULTADO</strong>, lo vencedor receberá seus ganhos <strong>AUTOMATICA E DIRETAMENTE</strong>{" "}
                  em sua carteira !
                </p>
              </div>
            </div>
            <div className="about-imgcontainer">
              <Image
                src="/image/explication-image.png"
                className="presentationImg1"
                alt="winner of defi lottery cash prize easy money "
                width={800}
                height={400}
              />
            </div>
          </div>
          <div id="progress">
            <div className="progress-textcontainer">
              <div className="textTitleRight">
                <h2>O curso</h2>
              </div>
              <div className="textParagrapheRight">
                <p>
                O sorteio acontece todas as sextas-feiras às (horário) UTC+1, O vencedor é sorteado por meio de um{" "}
                  <strong className="linkText">
                    <a href="#smartcontract">contrato inteligente</a>
                  </strong>
                  . As NFTs de hortelã durante a semana se tornarão obsoletas após o sorteio e uma nova coleção estará disponível no{" "}
                  <strong className="linkText">
                    <a href="#">market place</a>
                  </strong>
                  . O vencedor será nomeado no site (
                  <strong className="linkText">
                    <a href="#">aqui</a>
                  </strong>
                  ) e no discord no momento do sorteio.
                </p>
              </div>
            </div>
            <div className="progress-imgcontainer">
              <Image
                src="/image/weeklyroadmap-image.png"
                alt="road map project of defi lottery money loto"
                className="roadmap-textIllustration"
                width={900}
                height={500}
              />
            </div>
          </div>
          <div id="smartcontract">
            <div className="smartcontract-textcontainer">
              <div className="textTitleLeft">
                <h2>O contrato inteligente</h2>
              </div>
              <div className="textParagrapheLeft">
                <p>
                O blockchain e a web 3.0 nos oferecem a possibilidade de garantir a segurança de uma loteria confiável e segura através do uso de um contrato inteligente. O contrato inteligente será implantado, o dinheiro das moedas será{" "}
                  <strong>seguro</strong> sno contrato inteligente. Para garantir total transparência, o código do contrato inteligente será
                  <strong>acessível a todos</strong> para que você possa decifrar essas linhas de código para garantir que não haja espaço para fraudes. O sorteio para o vencedor também será feito no contrato inteligente com a função de hash keccack256,{" "}
                  <strong>que não podemos controlar/modificar</strong>
                  O sorteio será baseado no <strong>TOTAL HASHARD</strong>
                </p>
              </div>
            </div>
            <div className="smartcontract-imgcontainer">
              <Image
                src="/image/smartcontract-image.png"
                alt="security smart contract developper blockchain work on security defi lottery"
                className="imgsmartcontract"
                width={500}
                height={500}
              />
            </div>
          </div>
          <div id="mintnft">
            <div className="mintnft-textcontainer">
              <div className="textTitleRight">
                <h2>A hortelã do NFT</h2>
              </div>
              <div className="textParagrapheRight">
                <p>
                O NFT Mint será feito em <strong>nosso site</strong> na seção do mercado NFT que você pode encontrar logo acima O dinheiro da moeda será imediatamente armazenado no contrato inteligente após sua compra, sem intermediário, e seus fundos estarão{" "}
                  <strong>seguros</strong>
                  Você pode ver isso no contrato inteligente, só podemos pagar um ao outro nossas respectivas ações usando{" "}
                  <strong>PaymentSplitter</strong>, o que facilitará nossa dívida...
                </p>
              </div>
            </div>
            <div className="mintnft-imgcontainer">
              <Image
                src="/image/mint-image.png"
                alt="mint nft ticket defi lottery for win cash prize"
                className="imgmintnft"
                width={500}
                height={500}
              />
            </div>
          </div>
        </section>
        <footer>
          <div id="deuxiemeTrait" />
          <div className="footer-container">
            <div className="footer-presentation-defi">
              <div className="footer-presentation-defi-description">
                <h3 className="footer-presentation-defi-h3">
                  <i className="fa-solid fa-ticket" /> DeFi Lottery
                </h3>
                <h4 className="footer-presentation-defi-h4">
                DeFi Lottery, loteria baseada na tecnologia blockchain e protegida pelo uso de um contrato inteligente
                </h4>
              </div>
            </div>
            <div className="footer-credits">
              <h4>
                <a href="#about">Sobre</a>
              </h4>
              <h4>
                <a href="">Contate-Nos</a>
              </h4>
              <h4>
                <a href="">Whitepaper</a>
              </h4>
              <h4>
                <a href="credits.html">Créditos</a>
              </h4>
              {/* <form action="data.php" method="POST" class="footer-form">
                    <input style="cursor:text" type="email" name="email" class="footer-form-input" placeholder="E-mail">
                    <textarea style="cursor:text" type="textarea" class="footer-form-textarea" placeholder="Votre message"></textarea>
                    <button class="footer-form-btn"><a>Envoyer</a></button>
                </form> */}
            </div>
          </div>
          <div id="deuxiemeTrait" />
          <div id="copyrightEtIcons">
            <div id="copyright">
              <span title="Jeunes Entrepreneurs">© All Rights Reserved</span>
            </div>
            <div id="icons">
              <a
                href="https://twitter.com/DeFi_Lottery"
                title="Accédez à notre twitter"
              >
                <i className="fa-brands fa-twitter" />
              </a>
              <a
                href="https://www.youtube.com/?hl=FR"
                title="Accédez à notre chaine youtube"
              >
                <i className="fa-brands fa-youtube" />
              </a>
              <a
                href="https://discord.gg/GqsyHETQM2"
                title="Accédez à notre discord communautaire officiel"
              >
                <i className="fa-brands fa-discord" />
              </a>
            </div>
          </div>
        </footer>
      </div>
  )
}
