import Head from 'next/head'
import Link from 'next/link'
import Script from 'next/script'
import Image from 'next/image'



export default function Home() { 
  
  

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <header>
          <nav>
            <ul>
              <li id="logo">
                <a href="#">
                  <i className="fa-solid fa-ticket" /> DeFi Lottery
                </a>
              </li>
              <div className="action">
                <div className="profile" >
                  <li className="reglage">
                    <a title="Réglages du site">
                      <i className="fa-solid fa-gear" />
                    </a>
                  </li>
                </div>
                <div className="menu">
                  <ul>
                    <div className="action2">
                      <div className="profile2" >
                        <li>
                          <i className="fa-solid fa-globe" /> Langue{" "}
                          <i className="fa-solid fa-caret-right" />
                        </li>
                        <div className="menulang">
                          <ul>
                            <li>
                              <a className="langa" href="#">
                                FranCais <i className="fa-solid fa-circle-check" />
                              </a>
                            </li>
                            <li>
                              <a className="langa" href="ENindex.html">
                                Anglais
                              </a>
                            </li>
                            <li>
                              <a className="langa" href="BRindex.html">
                                Bresilien
                              </a>
                            </li>
                            <li>
                              <i className="fa-solid fa-arrow-left" /> Precedent
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                    <div className="actionclose" >
                      <ul>
                        <li>
                          <i className="fa-solid fa-xmark" /> Fermer
                        </li>
                      </ul>
                    </div>
                  </ul>
                </div>
              </div>
              <div className="iconsnavbartwitter">
                <a
                  className="logotwitter"
                  href="https://twitter.com/?lang=fr"
                  title="Accédez à notre twitter"
                >
                  <i className="fa-brands fa-twitter" />
                </a>
              </div>
              <div className="iconsnavbardiscord">
                <a
                  className="logodiscord"
                  href="https://discord.gg/GqsyHETQM2"
                  title="Accédez à notre discord communautaire officiel"
                >
                  <i className="fa-brands fa-discord" />
                </a>
              </div>
              <li id="whitepaper">
                <a target="_blank" href="youtube.com" title="Accédez au White Paper">
                  White Paper
                </a>
              </li>
              <li id="apropos">
                <a href="#about" title="Pour mieux comprendre notre projet">
                  a propos
                </a>
              </li>
              <li className="nav-roadmap">
                <a href="FRroadmap.html">Road Map</a>
              </li>
              <button id="btnmarketplace" title="Accédez à la collection NFT">
                <Link href="/Mint">
                <a>Marketplace NFT</a>
                </Link>
              </button>
            </ul>
          </nav>
          <div id="mainPage-home">
            <div className="mainPage-text">
              <h1>DeFi Lottery</h1>
              <div id="premierTrait" />
              <h3>100% Décentralisée, 100% Sécurisé</h3>
              <h3>
                Loterie géré par <strong>vous</strong>
              </h3>
            </div>
            {/* <div class="mainPage-btn">
                <ul>
                    <li><a class="mainPage-btn-discover" href="#">YOU</a></li>
                    <li><a class="mainPage-btn-gettingstart" href="#">FUCK</a></li>
                </ul>
            </div> */}
          </div>
        </header>
        <div className="splitchange">
          <h4>
            <a className="splitchange-more" href="#presentation">
              {" "}
              En apprendre plus sur le projet{" "}
              <i className="fa-solid fa-chevron-down" />
            </a>
          </h4>
        </div>
        <section id="presentation">
          <div id="about">
            <div className="about-textcontainer">
              <div className="textTitleLeft">
                <h2>Explication du projet</h2>
              </div>
              <div className="textParagrapheLeft">
                <p>
                  DeFi Lottery est une Lottery <strong>100% Décentralisée</strong>,
                  nous utilisons les technologies de la{" "}
                  <strong>BLOCKCHAIN et des NFTs</strong>.Les NFTs DeFi Lottery{" "}
                  <strong>NE SONT PAS de simples png,jpeg</strong>,ce sont des{" "}
                  <strong>tickets d&apos;entré</strong> à une lotterie hebdomadaire ! Après
                  le tirage,vous pouvez garder <strong>VOS NFTs, VOS tickets</strong>
                  .Une fois un gagnant tiré de façon <strong>&quot;automatique&quot;</strong>,
                  et de façon à ce que{" "}
                  <strong>PERSONNE NE PEUT INFLUENCER LE RESULTAT</strong>, le gagnant
                  recevr ses gains <strong>AUTOMATIQUEMENT ET DIRECTEMENT</strong>{" "}
                  dans son wallet !
                </p>
              </div>
            </div>
            <div className="about-imgcontainer">
              <Image
                src="/image/explication-image.png"
                className="presentationImg1"
                alt="winner of defi lottery cash prize easy money "
                width={800}
                height={400}
              />
            </div>
          </div>
          <div id="progress">
            <div className="progress-textcontainer">
              <div className="textTitleRight">
                <h2>Le déroulement</h2>
              </div>
              <div className="textParagrapheRight">
                <p>
                  Le tirage au sort se passe chaque vendredi à (heure) UTC+1, Le
                  gagnant est tiré au sort via un{" "}
                  <strong className="linkText">
                    <a href="#smartcontract">smart contract</a>
                  </strong>
                  . Les NFTs mint durant la semaine deviendront obsolète après le
                  tirage et une nouvelle collection sera disponible sur la{" "}
                  <strong className="linkText">
                    <a href="#">market place</a>
                  </strong>
                  . Le gagnant seront nommés sur le site (
                  <strong className="linkText">
                    <a href="#">ici</a>
                  </strong>
                  ) et sur le discord à l&apos;heure du tirage.
                </p>
              </div>
            </div>
            <div className="progress-imgcontainer">
              <Image
                src="/image/weeklyroadmap-image.png"
                alt="road map project of defi lottery money loto"
                className="roadmap-textIllustration"
                width={900}
                height={500}
              />
            </div>
          </div>
          <div id="smartcontract">
            <div className="smartcontract-textcontainer">
              <div className="textTitleLeft">
                <h2>Le Smart Contract</h2>
              </div>
              <div className="textParagrapheLeft">
                <p>
                  La blockchain et le web 3.0 nous offrent la possibilité de garantir
                  la sécurité d&apos;une loterie fiable et sécurisée grâce à l&apos;utilisation
                  d&apos;un contrat intelligent (smart contract en anglais) Le contrat
                  intelligent sera déployé, l&apos;argent des monnaies sera{" "}
                  <strong>sécurisé</strong> sur le contrat intelligent. Afin de
                  garantir une transparence totale, le code du contrat intelligent
                  sera
                  <strong>accessible à tous</strong> vous pourrez donc déchiffrer ces
                  lignes de code pour vous assurer que nous ne laissons pas de place
                  aux arnaques. Le tirage au sort du gagnant se fera également sur le
                  contrat intelligent avec la fonction de hachage keccack256,{" "}
                  <strong>que nous ne pouvons pas contrôler/modifier</strong>
                  Le tirage sera basé sur le <strong>HASHARD TOTAL</strong>
                </p>
              </div>
            </div>
            <div className="smartcontract-imgcontainer">
              <Image
                src="/image/smartcontract-image.png"
                alt="security smart contract developper blockchain work on security defi lottery"
                className="imgsmartcontract"
                width={500}
                height={500}
              />
            </div>
          </div>
          <div id="mintnft">
            <div className="mintnft-textcontainer">
              <div className="textTitleRight">
                <h2>Le mint du NFT</h2>
              </div>
              <div className="textParagrapheRight">
                <p>
                  Le mint de NFT se fera sur <strong>notre site</strong> dans la
                  section marketplace NFT que vous pouvez retouver juste au-dessus
                  L&apos;argent des mint sera imméditament stocké sur le smart contract
                  suite à votre achat,sans intermédiaire,et vos fonds seront{" "}
                  <strong>sécurisés</strong>
                  Vous pouvez le voir sur le smart contract,nous ne pouvons que nous
                  verser nos parts repspectives à l&apos;aide de{" "}
                  <strong>PaymentSplitter</strong>,ce qui va faciliter nos dû...
                </p>
              </div>
            </div>
            <div className="mintnft-imgcontainer">
              <Image
                src="/image/mint-image.png"
                alt="mint nft ticket defi lottery for win cash prize"
                className="imgmintnft"
                width={500}
                height={500}
              />
            </div>
          </div>
        </section>
        <footer>
          <div id="deuxiemeTrait" />
          <div className="footer-container">
            <div className="footer-presentation-defi">
              <div className="footer-presentation-defi-description">
                <h3 className="footer-presentation-defi-h3">
                  <i className="fa-solid fa-ticket" /> DeFi Lottery
                </h3>
                <h4 className="footer-presentation-defi-h4">
                  DeFi Lottery, lotterie basé sur la technologie blockchain et
                  sécurisé via l&apos;utiisation d&apos;un smart contract
                </h4>
              </div>
            </div>
            <div className="footer-credits">
              <h4>
                <a href="#about">À propos</a>
              </h4>
              <h4>
                <a href="">Nous Contacter</a>
              </h4>
              <h4>
                <a href="">Whitepaper</a>
              </h4>
              <h4>
                <a href="credits.html">Crédits</a>
              </h4>
              {/* <form action="data.php" method="POST" class="footer-form">
                    <input style="cursor:text" type="email" name="email" class="footer-form-input" placeholder="E-mail">
                    <textarea style="cursor:text" type="textarea" class="footer-form-textarea" placeholder="Votre message"></textarea>
                    <button class="footer-form-btn"><a>Envoyer</a></button>
                </form> */}
            </div>
          </div>
          <div id="deuxiemeTrait" />
          <div id="copyrightEtIcons">
            <div id="copyright">
              <span title="Jeunes Entrepreneurs">© All Rights Reserved</span>
            </div>
            <div id="icons">
              <a
                href="https://twitter.com/DeFi_Lottery"
                title="Accédez à notre twitter"
              >
                <i className="fa-brands fa-twitter" />
              </a>
              <a
                href="https://www.youtube.com/?hl=FR"
                title="Accédez à notre chaine youtube"
              >
                <i className="fa-brands fa-youtube" />
              </a>
              <a
                href="https://discord.gg/GqsyHETQM2"
                title="Accédez à notre discord communautaire officiel"
              >
                <i className="fa-brands fa-discord" />
              </a>
            </div>
          </div>
        </footer>
      </div>
  )
}
