import Head from 'next/head'
import Footer from '../components/Accueil/FR/Footer'
import Header from '../components/Accueil/FR/Header'
import SectionPresentation from '../components/Accueil/FR/SectionPresentation'



export default function Home() { 
  
  

  return (
    <div>
      <Head>
        <title>DeFi Lottery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="image/logo-onglet.jpg"/>
      </Head>
      <Header/>
        <div className="splitchange">
          <h4>
            <a className="splitchange-more" href="#presentation">
              {" "}
              En apprendre plus sur le projet{" "}
              <i className="fa-solid fa-chevron-down" />
            </a>
          </h4>
        </div>
        <SectionPresentation/>
        <Footer/>
      </div>
  )
}
