import Head from 'next/head';
import Footer from '../components/Accueil/FR/Footer';
import MintFR from '../components/Mint/FR/MintFR';


export default function Mint() {

    return (
        <div >
            <Head>
              <title>DeFi Lottery</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="image/logo-onglet.jpg"/>
            </Head>
            <MintFR/>
            <Footer/>
        </div >
    )
}
