import Head from 'next/head';
import Footer from '../components/Accueil/FR/Footer';
import MintGB from '../components/Mint/GB/MintGB';


export default function Mint_GB() {

    return (
        <>
            <Head>
              <title>DeFi Lottery</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="image/logo-onglet.jpg"/>
            </Head>
            <MintGB/>
            <Footer/>
        </>
    )
}
