import Head from 'next/head';
import Footer from '../components/Accueil/FR/Footer';
import MintBR from '../components/Mint/BR/MintBR';


export default function Mint_BR() {

    return (
        <>
            <Head>
              <title>DeFi Lottery</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="image/logo-onglet.jpg"/>
            </Head>
            <MintBR/>
            <Footer/>
        </>
    )
}
